// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7BNLhOCSYoGsa1m1KclgLAa3alDnhFNE',
    appId: '1:214766471130:web:3a1ff248b9432643fe22e3',
    messagingSenderId: '214766471130',
    projectId: 'chat-app-78ad8',
    authDomain: 'chat-app-78ad8.firebaseapp.com',
    storageBucket: 'chat-app-78ad8.firebasestorage.app',
    measurementId: 'G-QN37B5X6JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD70ysrwP_S3JkC-JTgi4kYLrS_C3sWl2o',
    appId: '1:214766471130:android:0ea6e8d8e1436fdffe22e3',
    messagingSenderId: '214766471130',
    projectId: 'chat-app-78ad8',
    storageBucket: 'chat-app-78ad8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDnV4VAu09Zh6QXTUipuJZhPU3uX2N-G4',
    appId: '1:214766471130:ios:e5067b3e33fc027cfe22e3',
    messagingSenderId: '214766471130',
    projectId: 'chat-app-78ad8',
    storageBucket: 'chat-app-78ad8.firebasestorage.app',
    iosBundleId: 'com.example.mediwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDnV4VAu09Zh6QXTUipuJZhPU3uX2N-G4',
    appId: '1:214766471130:ios:568d220b368d42e4fe22e3',
    messagingSenderId: '214766471130',
    projectId: 'chat-app-78ad8',
    storageBucket: 'chat-app-78ad8.firebasestorage.app',
    iosBundleId: 'com.example.flutterUiDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC_Jhl8A5BZJKiaN77-er4UIQTbNFhRKA',
    appId: '1:214766471130:web:4b9333081efce320fe22e3',
    messagingSenderId: '214766471130',
    projectId: 'chat-app-78ad8',
    authDomain: 'chat-app-78ad8.firebaseapp.com',
    storageBucket: 'chat-app-78ad8.firebasestorage.app',
    measurementId: 'G-G57X32YMKK',
  );
}
